CREATE USER dev WITH PASSWORD 'vmware';
CREATE DATABASE demo WITH OWNER dev;
GRANT ALL PRIVILEGES ON DATABASE demo TO dev;

\c demo

CREATE TABLE IF NOT EXISTS account (
id SERIAL PRIMARY KEY,
username VARCHAR(50) NOT NULL,
name VARCHAR(200) NOT NULL,
email VARCHAR(200) NOT NULL
);
