FROM dvonthenen/mesos-dev:0.25.0
MAINTAINER David vonThenen (EMCCODE)

ENTRYPOINT cd /isolator/isolator && \
    ./bootstrap && \
    rm -Rf build && \
    mkdir build && \
    cd build && \
    ../configure --with-mesos-root=/mesos --with-mesos-build-dir=/mesos && \
    make
