CREATE USER dev WITH PASSWORD 'vmware';
CREATE DATABASE demo WITH OWNER dev;
GRANT ALL PRIVILEGES ON DATABASE demo TO dev;

\c demo dev

CREATE TABLE IF NOT EXISTS message (
id SERIAL PRIMARY KEY,
client VARCHAR(200) NOT NULL,
received_message VARCHAR(200) NOT NULL,
sent_message VARCHAR(200) NOT NULL
);
